- name: HTML5
  logo: HTML5
  url: https://developer.mozilla.org/docs/Web/HTML
  color: E34F26
  projects:
    - https://github.com/franvarney/whitiescarcare.com

- name: JavaScript
  logo: JavaScript
  url: https://developer.mozilla.org/docs/Web/JavaScript
  color: F7DF1E
  projects:
    - https://github.com/franvarney/atom-color-describe

- name: LeetCode
  logo: LeetCode
  url: https://leetcode.com/
  color: F89F1B
  projects:
    - https://github.com/franvarney/cs-study
    - https://github.com/franvarney/leetcode-js

- name: Node.js
  logo: Node.js
  url: https://nodejs.org/
  color: 339933
  projects:
    - https://github.com/franvarney/franvarney-api
    - https://github.com/franvarney/hapi-treeize
    - https://github.com/franvarney/kultiv-api
    - https://github.com/franvarney/node-carquery-api

- name: React
  logo: React
  url: https://reactjs.org/
  color: 61DAFB
  projects:
    - https://github.com/franvarney/franvarney-client

- name: Unity
  logo: Unity
  url: https://unity.com/
  color: 000000
  projects:
    - https://github.com/franvarney/guard-your-garrison
    - https://github.com/franvarney/unity-tutorial-space-shooter